export const DATA = [
  { title: "Functional Component" },
  { title: "Class Component" },
  { title: "Styling" },
  { title: "Fonts" },
  { title: "Color App" },
  { title: "Flexbox" },
  { title: "Flex" },
  { title: "FlexDirection" },
  { title: "Justify Content" },
  { title: "Align Items" },
  { title: "Align Self" },
  { title: "flexwrap" },
  { title: "aligncontent" },
  { title: "flex basic,grow and shrink" },
  { title: "width and height" },
  { title: "Import Component" },
  { title: "View" },
  { title: "Text" },
  { title: "Image" },
  { title: "Image Background" },
  { title: "Activity Indicator" },
  { title: "Button" },
  { title: "Flat List" },
  { title: "Safe Area View" },
  { title: "Touchable Opacity" },
  { title: "Touchable Highlight" },
  { title: "Touchable Without Feedback" },
  { title: "Modal" },
  { title: "Picker" },
  { title: "Scroll View" },
  { title: "Section List" },
  { title: "Status Bar" },
  { title: "Text Input" },
  { title: "Keyboard Avoiding View" },
  { title: "Text Input" },
  { title: "Keyboard Avoiding View" },
  { title: "Text Input" },
  { title: "Keyboard Avoiding View" },
  { title: "Text Input" },
  { title: "Keyboard Avoiding View" },
  { title: "Text Input" },
  { title: "Keyboard Avoiding View" },
  { title: "Refresh Control" },
  { title: "VirtualizedList" },
  { title: "Switch" },
  { title: "Alert" },
  { title: "Appearance (Dark and Light mode)" },
  { title: "Share" },
  { title: "Dimension" },
  { title: "App State" },
  { title: "AccessiblityInfo (Text With Link)" },
  { title: "Animated" },
  { title: "App Registry" },
  { title: "Dev Setting" },
  { title: "Easing" },
  { title: "Interaction  Manager" },
  { title: "Keyboard" },
  { title: "Layout Animation" },
  { title: "Pan Responder" },
  { title: "Systrace" },
  { title: "Transforms" },
  { title: "Vibration" },
  { title: "Use Color Scheme" },
  { title: "Use window Dimension" },
  { title: "Back Handler  (Only Android)" },
  { title: "Permissions Android (Only Android)" },
  { title: "Toast Android (Only Android)" },
  { title: "Action Sheet IOS (Only ios)" },
  { title: "setting (Only ios)" },
  { title: "Web View" },
  { title: "Progress Bar (Only Android)" },
  { title: "Plat Form" },
  { title: "Custom Icon" },
  { title: "Asynce Storage" },
  { title: "Map" },
  { title: "Multi Language" },
  { title: "File System Access" },
  { title: "Google Sign in" },
  { title: "Fb Sign in" },
  { title: "Local Database" },
  { title: "Animation" },
  { title: "Switch Navigation" },
  { title: "Stack Navigation" },
  { title: "Botton Tab Navigation" },
  { title: "Navigation Drawer" },
  { title: "Fragment (Only Android)" },
  { title: "Run Time Permission (Only Android)" },
  { title: "Glober Scope Variable" },
  { title: "Get Current Date Time" },
  { title: "Restart / Reset Cureent Screen" },
  { title: "GeoLocations" },
  { title: "Camera" },
  { title: "Play Audio" },
  { title: "Net Info" },
  { title: "Get Device Information" },
  { title: "Make a Phone Call" },
  { title: "Change app icon (Only Android)" },
  { title: "Generate Signed APK" },
  { title: "Debugging Method" },
  { title: "Card View" },
  { title: "Grid View" },
  { title: "Searchable Drop Down" },
  { title: "Char and Graph" },
  { title: "Gradiant Component" },
  { title: "PopUp Dialog" },
  { title: "Date Picker" },
  { title: "Spinner" },
  { title: "Check Box" },
  { title: "Radio button" },
  { title: "Drop Down" },
  { title: "Top tab" },
  { title: "Carousel" },
  { title: "Bottom sheet" },
  { title: "Swiper" },
  { title: "SeekBar / Slider" },
  { title: "Progress Bar (Only Android)" },
  { title: "Rating" },
  { title: "React native Emoji" }
];
