export const DATA = [
  { title: "Functional Component" },
  { title: "Class Component" },
  { title: "Styling,Font ,Color" },
  { title: "Flex / FlexBox" },
  { title: "Flex Direction" },
  { title: "Layout Direction" },
  { title: "Justify Content" },
  { title: "Align Items" },
  { title: "Align Self" },
  { title: "Align content" },
  { title: "Flex Wrap" },
  { title: "Flex Basis, Grow, and Shrink" }, 
  { title: "Absolute & Relative Layout"},
  { title: "Width and Height" },
  { title: "Import Component" },
  { title: "Dimension" },
  { title: "Use window Dimension" },
  { title: "Plat Form" },
  { title: "View" },
  { title: "Safe Area View" },
  { title: "Card View" },
  { title: "Gradient Component" },
  { title: "Text" },
  { title: "AccessibilityInfo (Text With Link)" },
  { title: "Text Input" },
  { title: "Keyboard Avoiding View" },
  { title: "Keyboard" },
  { title: "React native Emoji" },
  { title: "Button" },
  { title: "Check Box" },
  { title: "Radio button" },
  { title: "Touchable Opacity" },
  { title: "Touchable Highlight" },
  { title: "Touchable Without Feedback" },
  { title: "Timer" },
  { title: "Switch" },
  { title: "Image" },
  { title: "Image Background" },
  { title: "Custom Icon" },
  { title: "Picker" },
  { title: "Date Picker" },
  { title: "Get Current Date Time" },
  { title: "SeekBar / Slider" },
  { title: "Web View" },
  { title: "Alert" },
  { title: "Toast Android (Only Android)" },
  { title: "Action Sheet IOS (Only ios)" },
  { title: "Share / Share app / Activity View" },
  { title: "Carousel / Image slider" },
  { title: "Swiper" },
  { title: "Bottom sheet" },
  { title: "Modal" },
  { title: "Context Menus" },
  { title: "PopUp Dialog / Custom Popup View" },
  { title: "Camera / Image picker" },
  { title: "Photo library multi selection" },
  { title: "MapView (google map / apple map)" },
  { title: "GeoLocations" },
  { title: "Drop Down" },
  { title: "Searchable Drop Down" },
  { title: "Net Info / Reachability" },
  { title: "Spinner (Only Android)" },
  { title: "Loader / Activity Indicator (Only iOS)" },
  { title: "Scroll View" },
  { title: "Transforms / View Transition" },
  { title: "Rating / RatingBar" },
  { title: "Top tab / Segmented Control" },
  { title: "Progress Bar (Only Android)" },
  { title: "Progress Bar (Only iOS)" },
  { title: "Gesture" },
  { title: "Neumorphism effect" },
  { title: "Char and Graph" },
  { title: "Easing" },
  { title: "Flat List / Table view" },
  { title: "Section List" },
  { title: "Refresh Control" },
  { title: "VirtualizedList" },
  { title: "Grid View / Collection view" },
  { title: "Vibration" },
  { title: "Play Audio" },
  { title: "Play Video" },
  { title: "Make a Phone Call" },
  { title: "Status Bar and Tool bar" },
  { title: "Navigation bar" },
  { title: "Switch Navigation" },
  { title: "Stack Navigation / Navigation" },
  { title: "Bottom Tab Navigation / tab bar" },
  { title: "Navigation Drawer / Side menu" },
  { title: "Fragment (Only Android)" },
  { title: "Restart / Reset Current Screen" },
  { title: "Split View" },
  { title: "Animated" },
  { title: "Animation" },
  { title: "Layout Animation" },
  { title: "Pan Responder" },
  { title: "Launch screen" },
  { title: "Use Color Scheme" },
  { title: "Get Device Information" },
  { title: "App State" },
  { title: "Appearance (Dark and Light mode)" },
  { title: "App Registry" },
  { title: "Dev Setting" },
  { title: "Interaction  Manager" },
  { title: "Systrace" },
  { title: "Back Handler  (Only Android)" },
  { title: "Run Time Permission (Only Android)" },
  { title: "Permissions Android (Only Android)" },
  { title: "setting (Only ios)" },
  { title: "AsyncStorage" },
  { title: "Multi Language" },
  { title: "File System Access" },
  { title: "Google Sign in" },
  { title: "Fb Sign in" },
  { title: "Local Database" },
  { title: "Global scope variable" },
  { title: "Change app icon (Only Android)" },
  { title: "Generate Signed APK" },
  { title: "Debugging Method" }
];

export const tableTypeData = [
  { title: "Basic" },
  { title: "Section" },
  { title: "Search Bar" },
  { title: "Implement Indexed" },
  { title: "Expandable Cells" },
  { title: "Grid / Collection View in Cell" },
  { title: "Pagination" },
  { title: "Add To Favorite / Multi selection" },
  { title: "Re arrange cell" },
  { title: "Pull to refresh" },
  { title: "Auto complete" },
  { title: "Swipe action" },
  { title: "cell hight dynamic" },
  { title: "Button action cell" },
  { title: "Flat / table view cell" },
  { title: "Build TikTok Feed" },
  { title: "Table view place holder" },
  { title: "Chat app table view" },
  { title: "Advance table view" },
  { title: "Skeleton loader skimmer effect" },
  { title: "Multiple custom cell" },
  { title: "Pop over table view" },
  { title: "Rating table view cell" },
  { title: "Reusable or generic tableView" },
  { title: "Update tableView data without reloading" },
  { title: "Table view header footer" },
  { title: "Switch table view cell" },
  { title: "Search and filter table view cell" },
  { title: "Text field in table view cell" },
  { title: "Lazy image loading in table view" },
  { title: "Crud option in table view cell" },
  { title: "Segment with tableView" },
  { title: "table view section date headers" },
  { title: "Table view cell animation" }
];
